# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.9]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} for pull requests
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/setup-python@v3
      with:
        ref: ${{ github.head_ref }}
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }} for push
      if: ${{ github.event_name == 'push' }}
      uses: actions/setup-python@v3
      with:
        ref: ${{ github.ref }}
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        make format
    - name: Test with pytest
      env:
        HYDRO_USERNAME: ${{ secrets.HYDRO_USERNAME }}
        HYDRO_PASSWORD: ${{ secrets.HYDRO_PASSWORD }}
      run: |
        make test-cov
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.11
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
